import 'action_visitor.dart';
import 'comparison_op_visitor.dart';
import 'direction_visitor.dart';
import 'expression_visitor.dart';
import 'function_visitor.dart';
import 'literal_visitor.dart';
import 'property_visitor.dart';
import 'statement_visitor.dart';
import 'widget_reference_visitor.dart';
import 'widget_type_visitor.dart';
import 'widget_visitor.dart';

final clickTypeVisitor = ClickTypeVisitor();
final expressionVisitor = ExpressionVisitor();
final widgetVisitor = WidgetVisitor();
final widgetTypeVisitor = WidgetTypeVisitor();
final literalVisitor = LiteralVisitor();
final comparisonOpVisitor = ComparisonOpVisitor();
final propertyVisitor = PropertyVisitor();
final functionVisitor = FunctionVisitor();
final statementVisitor = StatementVisitor();
final actionVisitor = ActionVisitor();
final singleDirectionVisitor = SingleDirectionVisitor();
final doubleDirectionVisitor = DoubleDirectionVisitor();
final referenceVisitor = WidgetReferenceVisitor();
final typeVisitor = WidgetTypeVisitor();
